### ISSUE TITLE
Add Creative Commons license

### ISSUE THREAD

**Issue by timcappalli** [passkeydeveloper/passkeys.dev#54]
Leaning towards [`CC BY-SA 2.5`](https://creativecommons.org/licenses/by-sa/2.5/) which is what Mozilla uses with MDN.

Any thoughts @MasterKale @dontcallmedom?

**Comment by MasterKale** [comment]
Looks like there's now [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) but so far this looks like a good license to get people to share the site around but also cite their sources.

**Comment by dontcallmedom** [comment]
+1 to align with MDN on CC BY-SA licensing for content - note that [MDN content is licensed under "v2.5 or any later version"](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license)
> the content is available under the terms of the [Creative Commons Attribution-ShareAlike license](https://creativecommons.org/licenses/by-sa/2.5/) (CC-BY-SA), v2.5 or any later version.

I would say it's also worth aligning on the [specific license MDN uses for code samples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license#code_samples), [public domain CC0](https://creativecommons.org/publicdomain/zero/1.0/) (otherwise, it makes it more challenging to integrate code samples into actual running code)
